[workspace]
members = ["."]
resolver = "2"

[package]
name = "obscura-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/h4ckf0r0day/obscura"
publish = false

[features]
default = []
render = ["obscura-js/render", "dep:taffy", "dep:cosmic-text"]
stealth = ["obscura-js/stealth"]

[lib]
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "2"

[dependencies]
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"
obscura-js = { path = "../obscura-js" }
taffy = { version = "=0.12.1", optional = true }
cosmic-text = { version = "=0.14.2", default-features = false, optional = true }

[patch.crates-io]
taffy = { path = "../../vendor/taffy" }
cosmic-text = { path = "../../vendor/cosmic-text" }

[profile.release]
panic = "unwind"
